server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  # Serve all routes under /auth
  location /auth {
    try_files $uri $uri/ /index.html;
  }

  # Redirect root to /auth/login
  location = / {
    return 301 /auth/login;
  }
}
